apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "realitychecker.fullname" . }}
  labels:
    {{- include "realitychecker.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:%v/%s" .Values.postgresql.host .Values.postgresql.port .Values.postgresql.database | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgresql.username | quote }}
  MAIN_REPEAT_INTERVAL: {{ .Values.config.mainRepeatInterval | quote }}
  LIMIT_PRICE: {{ .Values.config.limitPrice | quote }}
  APP_FILTER_DIRECTORY: {{ .Values.config.filterDirectory | quote }}
  SPRING_MAIL_HOST: {{ .Values.config.mailHost | quote }}
  SPRING_MAIL_PORT: {{ .Values.config.mailPort | quote }}
  SPRING_MAIL_USERNAME: {{ .Values.config.mailUsername | quote }}
  SPRING_MAIL_SMTP_AUTH: {{ .Values.config.mailSmtpAuth | quote }}
  SPRING_MAIL_SMTP_STARTTLS_ENABLE: {{ .Values.config.mailSmtpStarttlsEnable | quote }}
  SPRING_MAIL_SMTP_SSL_ENABLE: {{ .Values.config.mailSmtpSslEnable | quote }}
  EMAIL_ADDRESSES: {{ .Values.config.emailAddresses | quote }}
