{{- if or (not .Values.postgresql.existingSecret) (not .Values.mail.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "realitychecker.secretName" . }}
  labels:
    {{- include "realitychecker.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.postgresql.existingSecret }}
  {{ .Values.postgresql.passwordKey }}: {{ .Values.postgresql.password | quote }}
  {{- end }}
  {{- if not .Values.mail.existingSecret }}
  {{ .Values.mail.passwordKey }}: {{ .Values.mail.password | quote }}
  {{- end }}
{{- end }}
