--CREATE SCHEMA IF NOT EXISTS reality;

CREATE TABLE IF NOT EXISTS reality_server (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_name varchar(20),
    description varchar(50),
    updated_at timestamp
    );

CREATE TABLE IF NOT EXISTS advert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url varchar(1000),
    url_id varchar(20),
    active boolean,
    reality_server_id BIGINT,
    CONSTRAINT fk_reality_server FOREIGN KEY (reality_server_id) REFERENCES reality_server(id)
    );
