# All terraced family houses for sale within 30 km of Prague.
sreality.api-url=https://www.sreality.cz/api/v1/estates/search
sreality.web-url=https://www.sreality.cz
sreality.category-main=2
sreality.category-sub=37
sreality.category-type=1
sreality.locality-country-id=112
sreality.locality-entity-id=3468
sreality.locality-entity-type=municipality
sreality.locality-radius=30
sreality.block-inline-building=true
sreality.price-to=16000000